#nombre de la aplicación
spring.application.name=FeatureFlag API

# Puerto del servidor
server.port=8080

# PROPIEDADES DE JWT
security.jwt.secret =bWljbGF2ZXNlY3JldGFkZXVuYWNsYXZlcHJhcnByb3llY3RvZGVzcHJpbmdib290cXVldGVuZ2F1bmhhc2hncmFkZQ==

security.jwt.expiration=18000000
# media hora

#conexión BD postgresql
# ? URL de conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/FeatureDB

# ? Credenciales
spring.datasource.username=postgres
spring.datasource.password=12345

# ? Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ? Dialecto Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ? Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

