#nombre de la aplicación
spring.application.name=FeatureFlag API     

# Puerto del servidor
server.port=8080

# PROPIEDADES DE JWT
security.jwt.secret =123
security.jwt.expiration=18000000  # media hora

#conexión BD postgresql


